# This are the public keys of the age keypairs used to encrypt files
# You should have the private keys on your machine
keys:
  - &main age14uepygtepskwehywergh9fe9j2a3ytqd80y9r2ekfmett6rq3peqjtgxns
  - &infra age1rtdpdhuyrmzcvl5pqamjca6pxwdyzxnfrzg54zyle9w6j7c06yfsxmdhp3
creation_rules:
  # Allow any path in src to be encrypted
  - path_regex: src/.*
    key_groups:
      - age:
          - *main
          - *infra
